texi: un-comment indices.
wingo/fibers pull request #60
Opened 2022-06-16 17:00 UTC by HugoNikanor

I see no reason for not rendering the index that already is there.

The concept index is currently also empty, but I enabled it to in case something gets added to it later.

2022-07-23 19:36 UTC, emixa-d requested changes

2022-07-23 19:36 UTC, emixa-d commented on fibers.texi
> +@unnumbered Concept Index
I think including an index while it's still empty is a bit silly, but IMO go ahead with the rest!
I would like some confirmation from another reviewer on the location though.

2022-07-23 19:36 UTC, emixa-d commented on fibers.texi
> +@unnumbered Concept Index
(it can easily be re-added once there's actually some things inside)

2022-07-25 10:51 UTC, HugoNikanor commented
I re-commented the unused concept index.

-- 
Hugo Hörnquist
On Sat, Jul 23, 2022 at 12:36:45PM -0700, emixa-d wrote:
> @emixa-d commented on this pull request.
> 
> 
> 
> > @@ -1389,11 +1389,11 @@ Guile now has a solid concurrency story.  Use fibers, incorporate it
>  directly into your project, fork it, improve it: what happens now is
>  up to you.  Happy hacking and godspeed!
>  
> ***@***.*** @node Concept Index
> ***@***.*** @unnumbered Concept Index
> ***@***.*** @printindex cp
> ***@***.*** @node Function Index
> ***@***.*** @unnumbered Function Index
> ***@***.*** @printindex fn
> ***@***.*** Concept Index
> ***@***.*** Concept Index
> 
> (it can easily be re-added once there's actually some things inside)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/wingo/fibers/pull/60#discussion_r928157784
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

2022-07-25 11:21 UTC, emixa-d commented
Looks like there are some errors, according to the CI, could you fix them?

2022-07-25 13:03 UTC, HugoNikanor commented
I couldn't recreate the warning locally, but hopefully this fixes it.

2023-09-02 14:40 UTC, emixa-d commented
I've rebased it in <https://github.com/wingo/fibers/pull/95>. Assuming no negative review (and assuming I don't forget), I intend to merge it after 5 days.

2023-09-09 10:37 UTC, merged